workflow's update

diff --git a/.github/workflows/enforcer.yaml b/.github/workflows/enforcer.yaml
--- a/.github/workflows/enforcer.yaml
+++ b/.github/workflows/enforcer.yaml
@@ -4,28 +4,24 @@ name: 'enforcer'
 
 on:
   pull_request:
-    branches: [main, develop, alpha]
+    branches: [main, beta, alpha, staging]
 
 jobs:
   branch-policy-enforcement:
     runs-on: ubuntu-latest
     steps:
-      - name: Check if PR is to main
-        if: github.base_ref == 'main' && github.head_ref != 'alpha'
+      - name: Check Branch Flow
         run: |
-          echo "ERROR: You cannot merge to ${{ github.base_ref }} from ${{ github.head_ref }}. Please merge to 'alpha' first."
-          exit 1
-
-      - name: Check if PR is to alpha
-        if: github.base_ref == 'alpha' && github.head_ref != 'develop'
-        run: |
-          echo "ERROR: You cannot merge to ${{ github.base_ref }} from ${{ github.head_ref }}. Please merge to 'develop' first."
-          exit 1
-
-      - name: Check if PR is to develop
-        if: github.base_ref == 'develop' 
-        run: |
-          if [[ ! "${{ github.head_ref }}" =~ ^(feature|stack)/.+$ ]]; then 
+          if [[ "${{ github.base_ref }}" == "main" ]] && [[ "${{ github.head_ref }}" != "beta" ]]; then
+            echo "ERROR: You cannot merge to ${{ github.base_ref }} from ${{ github.head_ref }}. Please merge to 'beta' first."
+            exit 1
+          elif [[ "${{ github.base_ref }}" == "beta" ]] && [[ "${{ github.head_ref }}" != "alpha" ]]; then
+            echo "ERROR: You cannot merge to ${{ github.base_ref }} from ${{ github.head_ref }}. Please merge to 'alpha' first."
+            exit 1
+          elif [[ "${{ github.base_ref }}" == "alpha" ]] && [[ "${{ github.head_ref }}" != "staging" ]]; then
+            echo "ERROR: You cannot merge to ${{ github.base_ref }} from ${{ github.head_ref }}. Please merge to 'staging' first."
+            exit 1
+          elif [[ "${{ github.base_ref }}" == "staging" ]] && ( [[ "${{ github.head_ref }}" == "feature"* ]] || [[ "${{ github.head_ref }}" == "stack"* ]] || [[ "${{ github.head_ref }}" == "hotfix"* ]] ); then
             echo "ERROR: You cannot merge to ${{ github.base_ref }} from ${{ github.head_ref }}."
             exit 1
           fi
@@ -35,9 +31,7 @@ jobs:
     steps:
       - name: Validate title format
         run: |
-          if [[ ! "${{ github.event.pull_request.title }}" =~ ^\[(add|update|remove)\]:\[(stack|feature|hotfix)/[^]]+\](\[[a-zA-Z0-9-]+\])?::\ .+$ ]]; then
-            echo "ERROR: Invalid pull request title format. It should be '[add|update|remove]:[stack/feature/hotfix name][optional: taskid]:: [one line description]'."
+          if [[ ! "${{ github.event.pull_request.title }}" =~ ^\(add\|remove\|update\):\(stack\|feature\|hotfix\)/\([^:]+\):\(#[0-9]+,\)?::\ .+$ ]]; then
+            echo "ERROR: Invalid pull request title format. It should be '(add|remove|update):(stack/feature/hotfix)/(name of the stack or feature):(#ISSUE_ID, optional):: [one line description]'."
             exit 1
           fi
-
-
